name: Build and test library
on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
