name: Build and test library
on:
  push:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:ci

      - name: Lint files
        run: npm run lint:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
