name: PR checks
on:
  pull_request:
    branches: [main]

env:
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN }}

jobs:
  chromatic:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Chromatic project
        run: yarn chromatic
