on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - uses: actions/checkout@v2

      - uses: rlespinasse/github-slug-action@v3.x

      - name: Set version
        run: yarn version --new-version $(echo ${{ env.GITHUB_REF_SLUG }}|cut -c2-) --no-git-tag-version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build library
        run: yarn build

      - name: Release to GHPR
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
