on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          always-auth: "true"

      - uses: actions/checkout@v2

      - uses: rlespinasse/github-slug-action@v3.x

      - name: Set version
        run: npm version --new-version $(echo ${{ env.GITHUB_REF_SLUG }}|cut -c2-) --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Ignore .npmrc for publish step
        run: mv .npmrc .npmrc.temp

      - name: Release to GHPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHPR_TOKEN }}
